---
- name: Deploy Loki
  hosts: localhost
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Create Loki container
      docker_container:
        name: loki
        image: grafana/loki:latest
        ports:
          - "3100:3100"
        volumes:
          - /var/log/test:/var/log
        restart_policy: always

